snd-soc-tas2557-objs += tas2557-core.o 
snd-soc-tas2557-objs += tas2557-regmap.o 
snd-soc-tas2557-objs += tas2557-codec.o 
snd-soc-tas2557-objs += tas2557-misc.o 
snd-soc-tas2557-objs += tiload.o

obj-$(CONFIG_SND_SOC_TAS2557) += snd-soc-tas2557.o
